# Introduction {#intro}

The original idea of learning to rank is to serve the purpose of search engines. People usually use search engines as a very basic example of learning to rank due to their simple idea and explanation. However, there is some case that L2R apply to but have not been mentioned very much in the literature. In this short article, I will talk about Learning to Rank beyond Search Engines. Concretely, we can learn to rank without explicit query. Firstly, the general definition of a ranking function given by an ICML paper is stated as follows.

"Any system that presents results to a user, ordered by a utility function that the user cares about, is performing a ranking function" - Learning to Rank using Gradient Descent, ICML.

A common example is search engines, for example from the Web or from an intranet. For this problem, the data consists of a set of queries, and for each query, a set of returned documents. In the training phase, some query/document pairs are labeled for relevance ("excellent match", "good match", etc.). Only those documents returned for a given query are to be ranked against each other. Thus, rather than consisting of a single set of objects to be ranked amongst each other, the data is instead partitioned by a query. Here, the "utility function" is a query, it is an explicit function that tells the model to order documents from the most relevant documents to the least based on similarity measure.However, it is natural to think that, can we want to rank things without a query, or with implicit queries. For example, given a set of medical images, we want to order it from the most severe to the least. Is it a search engine problem? No, because no query, just have a list of documents (images). Is it a rank problem? Yes. Then what is the utility function here? The utility function is the definition of why one image is more severe than the others.

You can write citations, too. For example, we are using the **bookdown** package [@R-bookdown] in this sample book, which was built on top of R Markdown and **knitr** [@xie2015].
