const fs=require('fs'),assert=require('assert/strict'),A=require('./geometry.js'),E=require('./analysis-engine.js'),{LiveTube}=require('./audio.js');
const data=JSON.parse(fs.readFileSync(__dirname+'/sample.json'));A.setMotion(data.motion);const neutral=A.neutral(),names=['tip','dorsum','root'];
let maxHandleError=0,neutralErrors=[];
for(let f=0;f<210;f++){const frame=data.frames[f],m=A.model(frame,neutral);if(A.violation(frame,neutral,m))neutralErrors.push([f,A.violation(frame,neutral,m)]);for(const name of names){const p={...neutral,[name+'X']:.5,[name+'Y']:-.5};for(const other of names){const actual=A.handlePosition(other,p,frame),expected=frame.handles[other].map((v,k)=>v+(name===other?(k?-.5:.5):0));maxHandleError=Math.max(maxHandleError,Math.hypot(...actual.map((v,k)=>v-expected[k])));}}}
assert.deepEqual(neutralErrors,[]);assert(maxHandleError<.0001);
const cases=[];let checked=0;const previews=[];
for(const fi of [0,20,70,120,160,209]){const f=data.frames[fi],base=A.model(f,neutral);for(const key of Object.keys(neutral))for(const sign of [-1,1]){const p=A.constrain(f,neutral,{...neutral,[key]:sign*100}),m=A.model(f,p);assert.equal(A.violation(f,p,m),'',`${fi}/${key}/${sign}`);assert(p[key]>=f.bounds[key][0]-.0001&&p[key]<=f.bounds[key][1]+.0001);for(const n of names)assert(A.inHull(A.handlePosition(n,p,f),data.motion.hulls[n]));if(fi===0&&Math.abs(p[key])>.05)cases.push({key,request:sign*100,actual:+p[key].toFixed(3),valid:m.valid,peaks:m.valid?E.response(m).peaks:[]});checked++;}}
// Each handle bends the contour: its displacement is nonconstant, with other handles fixed.
const f=data.frames[0],base=A.model(f,neutral);previews.push({label:'MRI rest',frame:0,edits:neutral,model:base});
for(const name of names){let best=null;for(const d of ['X','Y'])for(const sign of [-1,1]){const p=A.constrain(f,neutral,{...neutral,[name+d]:sign*5}),m=A.model(f,p);const moved=Math.hypot(p[name+'X'],p[name+'Y']);if(!best||moved>best.moved)best={label:name,frame:0,edits:p,model:m,moved};}assert(best.moved>.2,`${name} needs usable movement`);const ds=best.model.organs[2][0].map((p,i)=>Math.hypot(...p.map((v,k)=>v-base.organs[2][0][i][k])));assert(Math.max(...ds)-Math.min(...ds)>.2,'Bending must not be a rigid translation');previews.push(best);}
// Persistent audio receives the SAME constrained geometry used for rendering.
const edited=previews.slice(1).filter(x=>x.model.valid).sort((a,b)=>b.moved-a.moved)[0];assert(edited);
const k=new LiveTube(48000),settle=new Float32Array(24000),a=new Float32Array(24000),b=new Float32Array(24000);
k.configure({...base,f0:130,voicing:1,breath:0,level:1,volume:.65,sequence:1});k.fill(settle);k.fill(a);k.configure({...edited.model,f0:130,voicing:1,breath:0,level:1,volume:.65,sequence:2});k.fill(settle);k.fill(b);assert.equal(k.sequence,2);
function spectrum(audio){const out=[];for(let h=1;h<=35;h++){let re=0,im=0;for(let i=0;i<audio.length;i++){const t=2*Math.PI*130*h*i/48000;re+=audio[i]*Math.cos(t);im+=audio[i]*Math.sin(t);}out.push(Math.hypot(re,im));}const norm=Math.hypot(...out);return out.map(x=>x/norm);}
const sa=spectrum(a),sb=spectrum(b),distance=Math.hypot(...sa.map((x,i)=>x-sb[i]));assert(distance>.03,`Bounded bend must change spectrum: ${distance}`);assert(a.every(Number.isFinite)&&b.every(Number.isFinite));const rms=x=>Math.sqrt(x.reduce((s,v)=>s+v*v,0)/x.length);assert(rms(a)>.001&&rms(b)>.001);assert(Math.max(...a.map(Math.abs),...b.map(Math.abs))<.65);
// Disconnected frames remain muted, with a short fade rather than hard switching.
k.configure({valid:false,sequence:3});k.fill(settle);assert(Math.max(...settle.slice(-1000).map(Math.abs))<1e-6);
// Rapidly vary actual clip geometry/source and verify no instability at 44.1/48 kHz.
for(const rate of [44100,48000]){const tube=new LiveTube(rate),block=new Float32Array(Math.round(rate/data.fps));for(const frame of data.frames){tube.configure({...A.model(frame,neutral),...frame.source,volume:.65});tube.fill(block);assert(block.every(Number.isFinite));assert(block.every(x=>Math.abs(x)<=.650001));}}
const report={status:'passed',neutralFrames:210,extremeControlChecks:checked,maxIndependentHandleErrorPx:maxHandleError,spectralDistance:distance,baselineRms:rms(a),editedRms:rms(b),sampleRates:[44100,48000],cases};console.log(JSON.stringify(report,null,2));fs.writeFileSync(__dirname+'/test-results.json',JSON.stringify(report,null,2));fs.writeFileSync(__dirname+'/preview-shapes.json',JSON.stringify(previews));
// A held vowel comparison: rest, brief gap, and bounded tongue bend at identical pitch.
function wav(path,parts){const samples=parts.flatMap(x=>Array.from(x)),buf=Buffer.alloc(44+samples.length*2);buf.write('RIFF');buf.writeUInt32LE(buf.length-8,4);buf.write('WAVEfmt ',8);buf.writeUInt32LE(16,16);buf.writeUInt16LE(1,20);buf.writeUInt16LE(1,22);buf.writeUInt32LE(48000,24);buf.writeUInt32LE(96000,28);buf.writeUInt16LE(2,32);buf.writeUInt16LE(16,34);buf.write('data',36);buf.writeUInt32LE(samples.length*2,40);samples.forEach((v,i)=>buf.writeInt16LE(Math.round(Math.max(-1,Math.min(1,v))*32767),44+i*2));fs.writeFileSync(path,buf);}
wav(__dirname+'/bounded-bend-demo.wav',[a,new Float32Array(9600),b]);
