/* DOM/audio stubs exercise app wiring; this is NOT a real browser rendering test. */
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const ids=new Map(),nodes=[];class Element{constructor(tag){this.tag=tag;this.children=[];this.attributes={};this.dataset={};this.style={};this.handlers={};this.value='';this.checked=false;this.clientWidth=400;this.classList={toggle(){}};nodes.push(this);}setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')ids.set(v,this);}appendChild(n){this.children.push(n);return n;}append(...a){a.forEach(x=>this.appendChild(x));}replaceChildren(){const clear=n=>{if(n.attributes?.id)ids.delete(n.attributes.id);n.children?.forEach(clear);};this.children.forEach(clear);this.children=[];}set innerHTML(s){for(const m of s.matchAll(/<(\w+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const e=new Element(m[1]);e.setAttribute('id',m[3]);this.appendChild(e);}}addEventListener(n,f){this.handlers[n]=f;}getContext(){return {drawImage(){}};}pause(){}play(){return Promise.resolve();}createSVGPoint(){return {x:0,y:0,matrixTransform(){return {x:this.x,y:this.y};}};}getScreenCTM(){return {inverse(){return {};}};}setPointerCapture(){}}
const html=fs.readFileSync(__dirname+'/index.html','utf8');for(const m of html.matchAll(/<(\w+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const e=new Element(m[1]);e.setAttribute('id',m[3]);e.checked=/\bchecked\b/.test(m[2]);}
const document={getElementById:id=>ids.get(id)||null,createElement:tag=>new Element(tag),createElementNS:(ns,tag)=>new Element(tag),createTextNode:t=>({textContent:t}),addEventListener(){},querySelectorAll(sel){const k=/\[data-([\w-]+)\]/.exec(sel)?.[1];return nodes.filter(n=>k&&k in n.dataset);}};
let received=[],currentProcessor;class MockProcessor{constructor(){this.port={postMessage(){}};}}
class MockNode{constructor(){this.port={postMessage:p=>{received.push(p);currentProcessor.port.onmessage({data:p});}};}connect(){return this;}disconnect(){}}
const blobs=new Map();class MockAudioContext{constructor(){this.sampleRate=48000;this.currentTime=0;this.destination={};this.audioWorklet={addModule:async url=>{const source=await blobs.get(url).text();const ctx=vm.createContext({AudioWorkletProcessor:MockProcessor,sampleRate:48000,registerProcessor:(name,P)=>currentProcessor=new P});vm.runInContext(source,ctx);}};}resume(){return Promise.resolve();}close(){return Promise.resolve();}createGain(){return {gain:{value:0,linearRampToValueAtTime(){},setTargetAtTime(){}},connect(){return this;}};}}
const ctx=vm.createContext({document,Image:class{constructor(){this.complete=true;this.naturalWidth=1;}},window:{AudioContext:MockAudioContext,addEventListener(){}},AudioWorkletNode:MockNode,ResizeObserver:class{observe(){}},Blob,URL:{createObjectURL:b=>{blobs.set('blob:test',b);return 'blob:test';},revokeObjectURL:u=>blobs.delete(u)},performance:{now:()=>100},setTimeout:()=>1,clearTimeout(){},requestAnimationFrame(){},console});
for(const name of ['sample.js','analysis-engine.js','audio.js','geometry.js','app.js'])vm.runInContext(fs.readFileSync(__dirname+'/'+name,'utf8'),ctx,{filename:name});
const run=s=>vm.runInContext(s,ctx);
(async()=>{run('atlas.onload()');assert.equal(ids.get('organPicker').children.length,5);assert.equal(ids.get('tongueParts').children.length,3);assert.equal(ids.get('handles').children.length,7);assert(ids.get('tipX'));run("state.tonguePart='root';selectOrgan('tongue');");assert(ids.get('rootX'));assert(!ids.get('tipX'));run("selectOrgan('jaw')");assert.equal(ids.get('tongueParts').hidden,true);
await run("setMode('synthesis');startSound()");assert(received.length);assert(currentProcessor);const initial=received.at(-1).areas.slice();run("state.tonguePart='dorsum';selectOrgan('tongue');applyEdit({...state.edits,dorsumY:2});syncSliders()");assert(received.at(-1).areas.some((v,i)=>Math.abs(v-initial[i])>.001));const block=new Float32Array(128);assert.equal(currentProcessor.process([],[[block]]),true);assert(block.every(Number.isFinite));
run("beginDrag('tip',{preventDefault(){},clientX:34,clientY:55,pointerId:1});$('anatomy').handlers.pointermove({clientX:31,clientY:54})");assert.equal(run('state.selected'),'tongue');assert.equal(run('state.tonguePart'),'tip');assert(Math.abs(run('state.edits.tipX'))>.01);run("$('anatomy').handlers.pointerup()");
for(const f of [20,70,120,160,209]){run(`setFrame(${f})`);assert.equal(run('A.violation(SAMPLE.frames[state.frame],state.edits,model)'), '');}
run("$('reset').onclick()");assert.equal(run('model.edited'),false);run('state.playing=true;state.time=.5;sendAudio()');assert.equal(received.at(-1).f0,run('SAMPLE.frames[50].source.f0'));run('pause()');assert.equal(received.at(-1).f0,130);
console.log(JSON.stringify({status:'passed',test:'DOM and AudioWorklet wiring stubs; no browser rendering',organButtons:5,tongueButtons:3,handles:7,audioConfigurations:received.length}));})().catch(e=>{console.error(e);process.exit(1);});
